# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='Title', max_length=20),
        ),
    ]
